name: Auto Scraper

on:
  schedule:
    - cron: "0 */12 * * *"  # rulează la fiecare 12 ore
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scraper
        run: python scraper_scores24.py

      - name: Commit updated JSON
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add scores24.json
          git commit -m "Auto update scores24.json"
          git push
